export type Locale = "en" | "tr";

export const translations = {
  en: {
    // Navbar
    reviewRequired: "Review Required",
    aiReady: "AI Ready",
    share: "Share",
    patientView: "Patient View",
    clinicianView: "Clinician View",
    discharge: "Discharge",

    // Patient Header
    mrn: "MRN",
    ageGender: "Age / Gender",
    dob: "DOB",
    discharged: "Discharged",
    physician: "Physician",
    dept: "Dept",
    diagnosis: "Diagnosis",
    living: "Living",
    caregiver: "Caregiver",
    yrs: "yrs",
    readmissionRisk: "Readmission Risk",
    lowHealthLiteracy: "Low Health Literacy",

    // Export
    print: "Print",
    exportPdf: "Export PDF",

    // Critical Alerts
    criticalSafetyAlerts: "Critical Safety Alerts",

    // Missing Info
    missingInformation: "Missing Information",

    // Clinician Summary
    clinicianSummary: "Clinician Summary",
    primaryDiagnosis: "Primary Diagnosis",
    medicationChanges: "Medication Changes",
    importantLabs: "Important Labs & Findings",
    redFlagRisks: "Red Flag Risks",
    followUpPlan: "Follow-up Plan",
    safetyNotes: "Safety Notes",

    // Follow-up cards
    labWork: "Lab Work",
    followUpVisit: "Follow-up Visit",
    monitoring: "Monitoring",
    daily: "Daily",

    // Patient Home Care
    patientHomeCare: "Patient Home Care Plan",
    yourHealthCondition: "Your Health Condition",
    medicineSchedule: "Medicine Schedule",
    morning: "Morning",
    afternoon: "Afternoon",
    evening: "Evening",
    beforeSleep: "Before Sleep",
    dailyTasks: "Daily Tasks",
    warningSignsCall: "Warning Signs — Call Hospital If:",
    appointmentsTests: "Appointments & Tests",
    importantReminders: "Important Reminders",

    // AI Explainability
    aiExplainability: "AI Explainability — Why These Risks Were Flagged",
    aiDisclaimer:
      "This AI-generated plan must be reviewed by a licensed clinician before patient distribution.",
    aiMethodology:
      "This discharge plan was generated by analyzing admission records, lab results, medication history, and clinical notes using a structured AI agent.",

    // Severity
    high: "High",
    medium: "Medium",
    low: "Low",
  },
  tr: {
    // Navbar
    reviewRequired: "İnceleme Gerekli",
    aiReady: "AI Hazır",
    share: "Paylaş",
    patientView: "Hasta Görünümü",
    clinicianView: "Klinisyen Görünümü",
    discharge: "Taburcu",

    // Patient Header
    mrn: "Dosya No",
    ageGender: "Yaş / Cinsiyet",
    dob: "Doğum Tarihi",
    discharged: "Taburcu Tarihi",
    physician: "Hekim",
    dept: "Bölüm",
    diagnosis: "Tanı",
    living: "Yaşam Durumu",
    caregiver: "Bakım Veren",
    yrs: "yaş",
    readmissionRisk: "Yeniden Yatış Riski",
    lowHealthLiteracy: "Düşük Sağlık Okuryazarlığı",

    // Export
    print: "Yazdır",
    exportPdf: "PDF İndir",

    // Critical Alerts
    criticalSafetyAlerts: "Kritik Güvenlik Uyarıları",

    // Missing Info
    missingInformation: "Eksik Bilgiler",

    // Clinician Summary
    clinicianSummary: "Klinisyen Özeti",
    primaryDiagnosis: "Birincil Tanı",
    medicationChanges: "İlaç Değişiklikleri",
    importantLabs: "Önemli Laboratuvar Sonuçları",
    redFlagRisks: "Kırmızı Bayrak Riskleri",
    followUpPlan: "Takip Planı",
    safetyNotes: "Güvenlik Notları",

    // Follow-up cards
    labWork: "Laboratuvar",
    followUpVisit: "Kontrol Muayenesi",
    monitoring: "İzleme",
    daily: "Günlük",

    // Patient Home Care
    patientHomeCare: "Hasta Evde Bakım Planı",
    yourHealthCondition: "Sağlık Durumunuz",
    medicineSchedule: "İlaç Takvimi",
    morning: "Sabah",
    afternoon: "Öğleden Sonra",
    evening: "Akşam",
    beforeSleep: "Uyku Öncesi",
    dailyTasks: "Günlük Görevler",
    warningSignsCall: "Uyarı İşaretleri — Şu Durumlarda Hastaneyi Arayın:",
    appointmentsTests: "Randevular ve Testler",
    importantReminders: "Önemli Hatırlatmalar",

    // AI Explainability
    aiExplainability: "AI Açıklanabilirlik — Riskler Neden İşaretlendi",
    aiDisclaimer:
      "Bu AI tarafından oluşturulan plan, hastaya dağıtılmadan önce lisanslı bir klinisyen tarafından incelenmelidir.",
    aiMethodology:
      "Bu taburcu planı, yatış kayıtları, laboratuvar sonuçları, ilaç geçmişi ve klinik notlar yapılandırılmış bir AI ajanı kullanılarak analiz edilerek oluşturulmuştur.",

    // Severity
    high: "Yüksek",
    medium: "Orta",
    low: "Düşük",
  },
} as const;

export type TranslationKey = keyof (typeof translations)["en"];
